### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by slarwise** [slarwise/erlang-include-finder#1]
- [x] Write an initial README.
- [ ] Make the README look nice 💅 Make a proper file tree etc.
- [ ] Specify the implementation in the README. Is the proposed solution good or are there alternatives to explore? 🤔
  - [ ] Which language, probably Python? 🐍
  - [ ] Should it have a command line interface? 👍
- [ ] Write tests
  - [ ] Create an example project that we can test our code on. 🏃‍♀️

**Comment by slarwise** [comment]
Command line interface for both creating the dependency file and for finding definitions would be nice. Then it's easy for any editor or other client that wants to find where something is defined to create a wrapper around the CLI.
